version: '2'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkinsplugin.Dockerfile
    user: root
    privileged: true
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      # Please update JENKINS_PASSWORD and JENKINS_USERNAME in .env file
      - JENKINS_USER=root
      - TZ=America/Toronto
      - JENKINS_ADMIN_ID=$JENKINS_USERNAME
      - JENKINS_ADMIN_PASSWORD=$JENKINS_PASSWORD
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
  vault:
    build: 
      context: .
      dockerfile: vault.Dockerfile 
    cap_add:
      - IPC_LOCK
    volumes:
      - type: volume
        source: vault_file
        target: /vault/file
      - type: volume
        source: vault_config
        target: /vault/config


volumes:
  jenkins_data:
    driver: local
  vault_file:
    driver: local
  vault_config:
    driver: local



